### ISSUE TITLE
Add support to include-before pandoc system

### ISSUE THREAD

**Issue by luanguimaraesla** [luanguimaraesla/pandocker#8]
Some parts of many works should be placed before table of contents and other things in the body of the work. I think is better define a new YAML template:

```yaml
pandocker:
  include-before:
     - example.before.md
     - example2.before.md

  body:
    - example.config.md
    - example.introduction.md
    - example.conclusion.md

pandoc:
	...
```
